In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('customer.csv')


In [3]:
df.sample(5)


age  gender   review education purchased
18   19    Male     Good    School        No
27   69  Female     Poor        PG        No
16   59    Male     Poor        UG       Yes
31   22  Female     Poor    School       Yes
8    65  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]


In [5]:
df.head()


review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [9]:
X_train

review education
39     Poor        PG
14     Poor        PG
45     Poor        PG
26     Poor        PG
27     Poor        PG
17     Poor        UG
48     Good        UG
21  Average        PG
12     Poor    School
46     Poor        PG
2      Good        PG
11     Good        UG
47     Good        PG
3      Good        PG
37  Average        PG
22     Poor        PG
35     Poor    School
29  Average        UG
34  Average    School
10     Good        UG
15     Poor        UG
40     Good    School
1      Poor        UG
25     Good    School
18     Good    School
8   Average        UG
41     Good        PG
19     Poor        PG
7      Poor    School
31     Poor    School
32  Average        UG
38     Good    School
28     Poor    School
9      Good        UG
16     Poor        UG
6      Good    School
33     Good        PG
13  Average    School
23     Good    School
43     Poor        PG

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [11]:
oe.fit(X_train)


OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [29]:
X_train = oe.transform(X_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [13]:
X_train


array([[0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.]])

In [14]:
oe.categories_


[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
X_train


array([[0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.]])

In [16]:
from sklearn.preprocessing import LabelEncoder


In [17]:
le = LabelEncoder()


In [18]:
le.fit(y_train)


LabelEncoder()

In [19]:
le.classes_


array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)


In [21]:
y_train

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

In [25]:
X_test = oe.transform(X_test)

In [26]:
X_test

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [2., 2.]])